# application.yml 
--- 
spring: 
  application: 
    name: infoUni
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
server:
  port: 8080
zuul:
  prefix: /info